/*
 * forward_acctwist_kin microblx function block (autogenerated, don't edit)
 */

#include <ubx.h>
#include <kdl/chain.hpp>
#include <kdl/frames.hpp>
#include <kdl/jntarrayvel.hpp>
#include <kdl_parser/kdl_parser.hpp>

/* from youbot_driver */
#include <motionctrl_jnt_state.h>

/* from std_types/kdl */
#include <kdl.h>

#define NR_OF_JOINTS 5


/* block meta information */
char forward_acctwist_kin_meta[] =
	" { doc='',"
	"   real-time=true,"
	"}";

/* declaration of block configuration */
ubx_config_t forward_acctwist_kin_config[] = {
	{ .name="root_link_acctwist", .type_name = "struct kdl_twist", .doc="accelleration of the root link" },
	{ .name="robot_structural_model", .type_name = "char", .doc="file containing urdf model of a robot " },
	{ NULL },
};

/* declaration port block ports */
ubx_port_t forward_acctwist_kin_ports[] = {
	{ .name="input_joint_acctwists", .in_type_name="double", .in_data_len=NR_OF_JOINTS, .doc="desired input joint accellerations"  },
	{ .name="input_link_poses", .in_type_name="struct kdl_frame", .in_data_len=NR_OF_JOINTS, .doc="link poses with respect to link tip frame coming from forward pose kinematics"  },
	{ .name="input_link_twists", .in_type_name="struct kdl_twist", .in_data_len=NR_OF_JOINTS, .doc="link twists with respect to link tip frame coming from forward twist kinematics"  },
	{ .name="input_joint_twists", .in_type_name="struct kdl_twist", .in_data_len=NR_OF_JOINTS, .doc="a joint rate contribution to a link twist with respect link tip frame coming from forward twist kinematics"  },
	{ .name="input_link_unit_twists", .in_type_name="struct kdl_twist", .in_data_len=NR_OF_JOINTS, .doc="unit twist defining motino subspace of the link"  },
	{ .name="output_link_acctwists", .out_type_name="struct kdl_twist", .out_data_len=NR_OF_JOINTS, .doc="link accelleration twists with respect to link tip frame computed by this block"  },
	{ NULL },
};

/* declare a struct port_cache */
struct forward_acctwist_kin_port_cache {
	ubx_port_t* input_joint_acctwists;
	ubx_port_t* input_link_poses;
	ubx_port_t* input_link_twists;
	ubx_port_t* input_joint_twists; //joint twist contribution
	ubx_port_t* input_link_unit_twists; //joint twist contribution
	ubx_port_t* output_link_acctwists;
};

/* declare a helper function to update the port cache this is necessary
 * because the port ptrs can change if ports are dynamically added or
 * removed. This function should hence be called after all
 * initialization is done, i.e. typically in 'start'
 */
static void update_port_cache(ubx_block_t *b, struct forward_acctwist_kin_port_cache *pc)
{
	pc->input_joint_acctwists = ubx_port_get(b, "input_joint_acctwists");
	pc->input_link_poses = ubx_port_get(b, "input_link_poses");
	pc->input_link_twists = ubx_port_get(b, "input_link_twists");
	pc->input_link_unit_twists = ubx_port_get(b, "input_link_unit_twists");
	pc->input_joint_twists = ubx_port_get(b, "input_joint_twists");
	pc->output_link_acctwists = ubx_port_get(b, "output_link_acctwists");
}


/* for each port type, declare convenience functions to read/write from ports */
def_read_arr_fun(read_joint_acctwists, double, NR_OF_JOINTS)
def_read_arr_fun(read_link_poses, struct kdl_frame, NR_OF_JOINTS)
def_read_arr_fun(read_joint_twists, struct kdl_twist, NR_OF_JOINTS)
def_read_arr_fun(read_link_twists, struct kdl_twist, NR_OF_JOINTS)
def_read_arr_fun(read_link_unit_twists, struct kdl_twist, NR_OF_JOINTS)
def_write_arr_fun(write_link_acctwists, struct kdl_twist, NR_OF_JOINTS)

/* block operation forward declarations */
int forward_acctwist_kin_init(ubx_block_t *b);
int forward_acctwist_kin_start(ubx_block_t *b);
void forward_acctwist_kin_stop(ubx_block_t *b);
void forward_acctwist_kin_cleanup(ubx_block_t *b);
void forward_acctwist_kin_step(ubx_block_t *b);


/* put everything together */
ubx_block_t forward_acctwist_kin_block = {
	.name = "forward_acctwist_kin",
	.type = BLOCK_TYPE_COMPUTATION,
	.meta_data = forward_acctwist_kin_meta,
	.configs = forward_acctwist_kin_config,
	.ports = forward_acctwist_kin_ports,

	/* ops */
	.init = forward_acctwist_kin_init,
	.start = forward_acctwist_kin_start,
	.stop = forward_acctwist_kin_stop,
	.cleanup = forward_acctwist_kin_cleanup,
	.step = forward_acctwist_kin_step,
};


/* forward_acctwist_kin module init and cleanup functions */
int forward_acctwist_kin_mod_init(ubx_node_info_t* ni)
{
	DBG(" ");
	int ret = -1;
	// ubx_type_t *tptr;

	// for(tptr=types; tptr->name!=NULL; tptr++) {
	// 	if(ubx_type_register(ni, tptr) != 0) {
	// 		goto out;
	// 	}
	// }

	if(ubx_block_register(ni, &forward_acctwist_kin_block) != 0)
		goto out;

	ret=0;
out:
	return ret;
}

void forward_acctwist_kin_mod_cleanup(ubx_node_info_t *ni)
{
	DBG(" ");
	// const ubx_type_t *tptr;

	// for(tptr=types; tptr->name!=NULL; tptr++)
	// 	ubx_type_unregister(ni, tptr->name);

	ubx_block_unregister(ni, "forward_acctwist_kin");
}

/* declare module init and cleanup functions, so that the ubx core can
 * find these when the module is loaded/unloaded */
UBX_MODULE_INIT(forward_acctwist_kin_mod_init)
UBX_MODULE_CLEANUP(forward_acctwist_kin_mod_cleanup)
